### PR TITLE
Added weights argument to star.makeTarget()

### PR DESCRIPTION
**Pull request by eacharles**
This addresses: https://github.com/rmjarvis/Piff/issues/99

### CODE REVIEW

**Comment by eacharles** [comment]
Hmm.  Do we need to add a test case that includes the weights?

**Comment by rmjarvis** [comment]
> Do we need to add a test case that includes the weights?

Yes.

**Comment by eacharles** [comment]
Hmm.   So the all the new code does is pass the weights argument in star.makeTarget() to the StarData c'tor.  

There isn't really a test that just tests that makeTarget() is doing the right thing.    In test_start.py makeTarget() is only used in the test_io().      

star.makeTarget() is used in a lot of places in higher level tests (test_optics, test_poly, test_wcs).   Is there any particular test or tests where it would make sense to supply weights?

**Comment by rmjarvis** [comment]
It looks like the `make_data` function in test_gsobject_model.py could be reworked to use this feature.  Right now it waits until the `Star` object is made and then fills in the weight image appropriately.  You could switch to passing in a weight to `makeTarget` at the start.

`make_gaussian_data` in test_pixel.py is similar.

**Comment by eacharles** [comment]
Hmm.   I can do something like:
```
    weight = galsim.Image(nside, nside, dtype=float, init_value=1./var)
    star = piff.Star.makeTarget(x=nside/2+nom_u0/du, y=nside/2+nom_v0/du,
                                u=fpu, v=fpv, scale=du, stamp_size=nside, weights=weights)

```
And that works fine for test_gs_object, which isn't really using the weight values
However, looking at similar changes in test_pixel  test_pixel.test_var() I'm concerned
about if the weights image is carrying around the correct metadata.


```
    weight = galsim.Image(nside, nside, dtype=float, init_value=1./var)
    print(weight, weight.array.mean(), var)
    star = piff.Star.makeTarget(x=nside/2+nom_u0/du, y=nside/2+nom_v0/du,
                                u=fpu, v=fpv, scale=du, stamp_size=nside, weight=weight)
    star.image.setOrigin(0,0)
    print(star.data.weight, star.data.weight.array.mean(), var)
    
    g.drawImage(star.image, method='no_pixel', use_true_center=False,
                offset=galsim.PositionD(nom_u0/du,nom_v0/du))
    print(star.data.weight, star.data.weight.array.mean(), var)    
    star.data.weight = star.image.copy()
    star.weight.fill(1./var)
    print(star.data.weight, star.data.weight.array.mean(), var)    

    # To generate output when running the unit test
    assert False # 
```
Produce this output:
```
galsim.Image(bounds=galsim.BoundsI(1,32,1,32), wcs=None, dtype=numpy.float64) 34.60207612456747 0.028900000000000006
galsim.Image(bounds=galsim.BoundsI(0,31,0,31), wcs=None, dtype=numpy.float64) 34.60207612456747 0.028900000000000006
galsim.Image(bounds=galsim.BoundsI(0,31,0,31), wcs=None, dtype=numpy.float64) 34.60207612456747 0.028900000000000006
galsim.Image(bounds=galsim.BoundsI(0,31,0,31), scale=0.5, dtype=numpy.float64) 34.60207612456747 0.028900000000000006

```

**Comment by eacharles** [comment]
I.e., It seems like the makeTarget() function is computing the meta data from the inputs, but adding the weights as it's own object with a possibly conflicting metadata.

**Comment by eacharles** [comment]
is what we want in makeTarget actually somethign like this code below?

```
        if weight is not None:
            weight = galsim.Image(weight.array.copy(), scale=image.scale)
            weight.setCenter(int(x+0.5), int(y+0.5))
```

**Comment by eacharles** [comment]
Ok, I've pushed changes that use the image scale to override the one in the weights object, as above.

**Comment by rmjarvis** [comment]
> weight = galsim.Image(nside, nside, dtype=float, init_value=1./var)

I think this line should include `scale=du`.

**Comment by eacharles** [comment]
Ok, i included that line
However, the star image and weights each carry their own metadata and makeTarget isn't really doing much to ensure that they are consistent.  I'm not sure how much you want to enforce that.

**Comment by rmjarvis** [comment]
Honestly, I don't think it matters. I just looked through the code for uses of weight, and I'm pretty sure we only ever use `weight.array` in anything that matters.  So if the user provides images with inconsistent metadata, it will prefer the image values.  This is a niche enough application, that I don't think it's probably worth adding any checks about this.  I wouldn't be surprised if the only user of this functionality is our own unit tests.

**Comment by eacharles** [comment]
You gonna merge it, or should i?

**Comment by rmjarvis** [comment]
Either way.  :)  Feel free to yourself in the future after an approval.  I usually leave it for the author to merge if they want, in case there is a last minute change they noticed that needs to be fixed or something.

**Pull request merged**
